### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by gongruike** [ashfurrow/C-41#21]
Hello, I clone the C-41 project, but I can't run it successfully in xcode. It seems like some class files are missing, like RVMViewModel class.
Could you tell me how to fix it, please?

**Comment by ashfurrow** [comment]
Hey @gongruike – did you get this figured out?

**Comment by gongruike** [comment]
yes, and thank you. I'm learning MVVM, it's a very good example.

发自我的 iPad
