### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by mailworks** [ashfurrow/C-41#24]
Hi，I find a reference cycle in `ASHTimerViewController` at line 62，remove @weakify(self)  will fix it ?

**Comment by ashfurrow** [comment]
Neat! Nice catch. Yeah, should do it. Wanna send a PR?

**Comment by mailworks** [comment]
Yeah. https://github.com/ashfurrow/C-41/pull/25

**Comment by mailworks** [comment]
closed
